name = "d20_round24"
version = "0.1.0"
defaultTargets = ["D20Round20", "D20Round21", "D20Round22", "D20Round23", "D20Round24"]

[[require]]
name = "formal_conjectures"
git = "https://github.com/google-deepmind/formal-conjectures.git"
rev = "8323e878b83fcd7f4a448256069352a265460d75"

[[lean_lib]]
name = "D20Round20"

[[lean_lib]]
name = "D20Round21"

[[lean_lib]]
name = "D20Round22"

[[lean_lib]]
name = "D20Round23"

[[lean_lib]]
name = "D20Round24"
