name = "d19_round20"
version = "0.1.0"
defaultTargets = ["D19Round20"]

[[require]]
name = "formal_conjectures"
git = "https://github.com/google-deepmind/formal-conjectures.git"
rev = "8323e878b83fcd7f4a448256069352a265460d75"

[[lean_lib]]
name = "D19Round20"
