import D23Round21
import D23Round37

#print axioms D23Round21.normSq_eq_zero_iff
#print axioms D23Round21.fullRank_scalar_norm_lt_sixteen
#print axioms D23Round21.smallGaussian_norm_cases
#print axioms D23Round21.fullRank_scalar_norm_cases
#print axioms D23Round37.fullRank_twiceGaussian_eight_points
#print axioms D23Round37.fullRank_twiceGaussian_norm_one_or_two
